version: '3.9'

services:
  app:
    build: .
    restart: always
    depends_on:
      - psqldb
    networks:
      - configServiceNetwork
      - garewaynestrabbit_gatewayNetwork
  psqldb:
    image: postgres:13
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: keshox
      POSTGRES_DB: configdb
    networks:
      - configServiceNetwork
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    logging:
      driver: none
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.codovstvo
      PGADMIN_DEFAULT_PASSWORD: egor
    ports:
      - "9705:80"
    networks:
      - configServiceNetwork

networks:
  configServiceNetwork:
    driver: bridge
  garewaynestrabbit_gatewayNetwork:
    external: true
