name: Docker Image CI

on:
  push:
    branches: [ "production" ]
jobs:
  push_to_registry:
    name: Build and Publish
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/production'
    steps:
      - name: Get release tag
        id: tag_name
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKER_PASS }} | docker login -u keshox --password-stdin
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: keshox/config:${{github.run_number}}
